export type Theme = {
  container: React.CSSProperties;
  tagline: React.CSSProperties;
  title: React.CSSProperties;
  paragraph: React.CSSProperties;
  subtitle: React.CSSProperties;
  description: React.CSSProperties;
  button: React.CSSProperties;
  headshot: React.CSSProperties;
  authorName: React.CSSProperties;
  authorHandle: React.CSSProperties;
};

export const themes: { [key: string]: Theme } = {
  theme1: {
    container: {
      backgroundColor: "#1a1a1a",
      padding: "30px",
      borderRadius: "15px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    tagline: { fontSize: "1.5rem", color: "#fff", fontStyle: "italic" },
    title: {
      fontSize: "3rem",
      color: "#ffdd57",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "10px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#ddd",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#ffdd57",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#ddd",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#ffdd57",
      color: "#1a1a1a",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #ffdd57",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#ffdd57", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#ddd", margin: "5px 0" },
  },
  theme2: {
    container: {
      backgroundColor: "#2e2e2e",
      padding: "40px",
      borderRadius: "10px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    tagline: {
      fontSize: "1.2rem",
      color: "#eee",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "2.8rem",
      color: "#00bfff",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.1rem",
      color: "#ccc",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.3rem",
      color: "#00bfff",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.1rem",
      color: "#ccc",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#00bfff",
      color: "#2e2e2e",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #00bfff",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#00bfff", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#ccc", margin: "5px 0" },
  },
  theme3: {
    container: {
      backgroundColor: "rgba(52, 58, 64, 0.8)",
      backdropFilter: "blur(10px)",
      padding: "50px",
      borderRadius: "10px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    tagline: {
      fontSize: "1.5rem",
      color: "#f8f9fa",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "3rem",
      color: "#ffc107",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#adb5bd",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#ffc107",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#adb5bd",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#ffc107",
      color: "#343a40",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #ffc107",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#ffc107", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#adb5bd", margin: "5px 0" },
  },
  theme4: {
    container: {
      backgroundColor: "rgba(245, 245, 245, 0.8)",
      backdropFilter: "blur(10px)",
      padding: "50px",
      borderRadius: "10px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "left",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    tagline: {
      fontSize: "1.2rem",
      color: "#333",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "2.8rem",
      color: "#ff5733",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.1rem",
      color: "#555",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.3rem",
      color: "#ff5733",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.1rem",
      color: "#555",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#ff5733",
      color: "#fff",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #ff5733",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#ff5733", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#555", margin: "5px 0" },
  },
  theme5: {
    container: {
      backgroundColor: "#e9ecef",
      padding: "40px",
      borderRadius: "15px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    tagline: {
      fontSize: "1.5rem",
      color: "#495057",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "3rem",
      color: "#28a745",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#6c757d",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#28a745",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#6c757d",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#28a745",
      color: "#fff",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #28a745",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#28a745", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#6c757d", margin: "5px 0" },
  },
  theme6: {
    container: {
      backgroundColor: "#ffffff",
      padding: "40px",
      borderRadius: "10px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    tagline: { fontSize: "1.5rem", color: "#333", fontStyle: "italic" },
    title: {
      fontSize: "3rem",
      color: "#007bff",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.2)",
      margin: "10px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#555",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#007bff",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#555",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#007bff",
      color: "#fff",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #007bff",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#007bff", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#555", margin: "5px 0" },
  },
  theme7: {
    container: {
      backgroundColor: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      padding: "50px",
      borderRadius: "10px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    tagline: {
      fontSize: "1.5rem",
      color: "#ffffff",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "3rem",
      color: "#ffffff",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#e0e0e0",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#ffffff",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#e0e0e0",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#ffffff",
      color: "#764ba2",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #ffffff",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#ffffff", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#e0e0e0", margin: "5px 0" },
  },
  theme8: {
    container: {
      backgroundColor: "#333333",
      padding: "40px",
      borderRadius: "15px",
      boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
      textAlign: "left",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    tagline: {
      fontSize: "1.5rem",
      color: "#ffffff",
      fontStyle: "italic",
      margin: "10px 0",
    },
    title: {
      fontSize: "3rem",
      color: "#ff3366",
      textShadow: "3px 3px 6px rgba(0, 0, 0, 0.8)",
      margin: "20px 0",
    },
    paragraph: {
      fontSize: "1.2rem",
      color: "#cccccc",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    subtitle: {
      fontSize: "1.5rem",
      color: "#ff3366",
      textTransform: "uppercase",
      margin: "10px 0",
    },
    description: {
      fontSize: "1.2rem",
      color: "#cccccc",
      lineHeight: "1.8",
      margin: "10px 0",
    },
    button: {
      backgroundColor: "#ff3366",
      color: "#ffffff",
      padding: "12px 24px",
      borderRadius: "8px",
      border: "none",
      cursor: "pointer",
      transition: "background-color 0.3s",
      margin: "20px 0",
    },
    headshot: {
      border: "2px solid #ff3366",
      borderRadius: "50%",
      margin: "10px 0",
    },
    authorName: { color: "#ff3366", fontWeight: "bold", margin: "5px 0" },
    authorHandle: { color: "#cccccc", margin: "5px 0" },
  },
};
